#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wine-ml-deployment
spec:
  selector:
    matchLabels:
      app: wine-ml-server
  replicas: 1
  template:
    metadata:
      labels:
        app: wine-ml-server
    spec:
      containers:
        - name: wine-ml-container
          #image: gcr.io/tensorflow-serving/resnet
          image: docker.io/joseemanuel/wine-ml:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: wine-ml-service
  name: wine-ml-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: wine-ml-server
  type: LoadBalancer
